/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all links
         * @description Get all links for the authenticated API client.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of links */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new short link
         * @description Only `destination` is strictly required. If `alias` is omitted, a random 8-character code will be generated.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example https://example.com */
                        destination: string;
                        /**
                         * @description Optional custom shortcode
                         * @example my-custom-alias
                         */
                        alias?: string;
                        /**
                         * @description Optional expiration timestamp (ms)
                         * @example 1735689600000
                         */
                        expiry?: number;
                        /**
                         * @description Whether to protect the link
                         * @example false
                         */
                        isProtected?: boolean;
                        /** @description Allowed emails if protected */
                        allowedEmails?: string[];
                        /**
                         * @description If true and the link is protected, emails all addresses in allowedEmails with the secure link upon creation.
                         * @example true
                         */
                        sendNotificationEmail?: boolean;
                        /**
                         * @description Maximum number of clicks before expiring
                         * @example 100
                         */
                        maxClicks?: number;
                        /** @description Tags for organization */
                        tags?: string[];
                        /**
                         * @description Internal notes
                         * @example Campaign link
                         */
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Link created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example custom-alias */
                            shortCode?: string;
                            /** @example https://links.erudio.in/custom-alias */
                            shortLink?: string;
                        };
                    };
                };
                /** @description Bad Request (e.g. alias already in use) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{shortCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a link
         * @description Permanently delete a short link and all associated analytics.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The short code of the link to delete */
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Link deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Link not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update an existing link
         * @description Update properties of a short link. Provide only the fields you wish to update.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The short code of the link to update */
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example https://example.com/updated */
                        destination?: string;
                        /**
                         * @description Optional new custom shortcode
                         * @example new-alias
                         */
                        alias?: string;
                        /**
                         * @description Optional expiration timestamp (ms)
                         * @example 1735689600000
                         */
                        expiry?: number;
                        /**
                         * @description Whether to protect the link
                         * @example true
                         */
                        isProtected?: boolean;
                        /** @description Allowed emails if protected */
                        allowedEmails?: string[];
                        /**
                         * @description Maximum number of clicks before expiring
                         * @example 500
                         */
                        maxClicks?: number;
                        /** @description Tags for organization */
                        tags?: string[];
                        /**
                         * @description Internal notes
                         * @example Updated notes
                         */
                        notes?: string;
                        /**
                         * @description Link status
                         * @example active
                         * @enum {string}
                         */
                        status?: "active" | "archived";
                    };
                };
            };
            responses: {
                /** @description Link updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Link not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get analytics
         * @description Get analytics for the authenticated user, optionally filtered by a specific short code.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional short code to filter analytics */
                    shortCode?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
